exclude: ^(\.devcontainer|.*\.terraform.*|.*\.tfstate.*)
repos:
# general
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
    exclude: \.ipynb$
  - id: check-yaml
  - id: pretty-format-json
    exclude: .+ipynb$
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-added-large-files
    args: [--maxkb=20480]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
  - id: shellcheck
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.18
  hooks:
  - id: shfmt
    args: [-w]
  - id: shellcheck
# python
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    args: [--recursive, --in-place, --wrap-summaries, '88', --wrap-descriptions, '88']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.9
  hooks:
  - id: ruff
    types_or: [python, pyi, jupyter]
    exclude: ^prototyping/
  - id: ruff-format
    types_or: [python, pyi, jupyter]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    args: [--check-untyped-defs, --non-interactive, --install-types, --no-namespace-packages]
    additional_dependencies: [types-setuptools]
# jupyter notebooks
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.1
  hooks:
  - id: nbqa-pyupgrade
    args: [--py310-plus]
# terraform
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.1
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
    require_serial: true
    args:
    - --args=-no-color
    - --hook-config=--retry-once-with-cleanup=true
    exclude: aws-backend
  - id: terraform_docs
    args:
    - --hook-config=--path-to-file=TF_README.md
    - --hook-config=--add-to-existing-file=true
    - --hook-config=--create-file-if-not-exist=true
    exclude: aws-backend
  - id: terraform_tflint
  - id: terraform_trivy
    args:
    - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore

- repo: local
  hooks:
  - id: test-app-unit
    name: test-app-unit
    entry: python -m pytest tests/test_app_unit.py
    language: system
    pass_filenames: false
