name: Format code

on:
  workflow_dispatch:
  # push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install poetry and dependencies
      run: |
        pip install poetry
        poetry install --no-interaction --no-ansi

    - name: Run pre-commit and check for changes
      id: check_changes
      run: |
        export SKIP=pytest-check
        poetry run pre-commit run --all-files
        git diff --exit-code || echo "changes"

    - name: Commit and push changes
      if: steps.check_changes.outputs.result == 'changes'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "CI code quality"
        git push
